// Automatically generated by eggmock v0.0.1-snapshot
#pragma once
extern "C" {
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
struct eggmock_aig_transfer {
  uint64_t ( *create_symbol )( void* data, uint64_t name );
  uint64_t ( *create_const )( void* data, bool value );
  uint64_t ( *create_not )( void* data, uint64_t id );
  uint64_t ( *create_and )( void* data , uint64_t, uint64_t, uint64_t);
};

struct eggmock_aig_rewrite_callback {
    void* data;
    eggmock_aig_transfer transfer;
};

struct eggmock_aig_rewrite {
    void* data;
    eggmock_aig_transfer transfer;
    void ( *rewrite )( void* data, uint64_t* roots, size_t roots_size, eggmock_aig_rewrite_callback callback );
};


struct eggmock_mig_transfer {
  uint64_t ( *create_symbol )( void* data, uint64_t name );
  uint64_t ( *create_const )( void* data, bool value );
  uint64_t ( *create_not )( void* data, uint64_t id );
  uint64_t ( *create_maj )( void* data , uint64_t, uint64_t, uint64_t);
};

struct eggmock_mig_rewrite_callback {
    void* data;
    eggmock_mig_transfer transfer;
};

struct eggmock_mig_rewrite {
    void* data;
    eggmock_mig_transfer transfer;
    void ( *rewrite )( void* data, uint64_t* roots, size_t roots_size, eggmock_mig_rewrite_callback callback );
};


struct eggmock_xmg_transfer {
  uint64_t ( *create_symbol )( void* data, uint64_t name );
  uint64_t ( *create_const )( void* data, bool value );
  uint64_t ( *create_not )( void* data, uint64_t id );
  uint64_t ( *create_xor )( void* data , uint64_t, uint64_t);  uint64_t ( *create_maj )( void* data , uint64_t, uint64_t, uint64_t);
};

struct eggmock_xmg_rewrite_callback {
    void* data;
    eggmock_xmg_transfer transfer;
};

struct eggmock_xmg_rewrite {
    void* data;
    eggmock_xmg_transfer transfer;
    void ( *rewrite )( void* data, uint64_t* roots, size_t roots_size, eggmock_xmg_rewrite_callback callback );
};


struct eggmock_xag_transfer {
  uint64_t ( *create_symbol )( void* data, uint64_t name );
  uint64_t ( *create_const )( void* data, bool value );
  uint64_t ( *create_not )( void* data, uint64_t id );
  uint64_t ( *create_and )( void* data , uint64_t, uint64_t, uint64_t);  uint64_t ( *create_xor )( void* data , uint64_t, uint64_t, uint64_t);
};

struct eggmock_xag_rewrite_callback {
    void* data;
    eggmock_xag_transfer transfer;
};

struct eggmock_xag_rewrite {
    void* data;
    eggmock_xag_transfer transfer;
    void ( *rewrite )( void* data, uint64_t* roots, size_t roots_size, eggmock_xag_rewrite_callback callback );
};


}
