use eggmock::{Aig, Mig, Node};

fn main() {
    println!("// Automatically generated by eggmock v{}", env!("CARGO_PKG_VERSION"));
    println!("{}", Mig::c_ffi());
    println!("{}", Aig::c_ffi());
}
