use eggmock::{gen, Aig, AigTransferFFI, Mig, RewriteCallback, RewriteFFI, Xag, Xmg};
use eggmock::gen::CFFI;

fn main() {
    println!("// Automatically generated by eggmock v{}", env!("CARGO_PKG_VERSION"));
    println!(r#"#pragma once"#);
    println!(r#"extern "C" {{"#);
    println!(r#"#include <stdint.h>"#);
    println!(r#"#include <stddef.h>"#);
    println!(r#"#include <stdbool.h>"#);
    println!("{}", gen::network_ffi::<Aig>());
    println!("{}", gen::network_ffi::<Mig>());
    println!("{}", gen::network_ffi::<Xmg>());
    println!("{}", gen::network_ffi::<Xag>());
    println!(r#"}}"#)
}
